### ISSUE TITLE
Use-Case Preis

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#1]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/casepreis

# Services
- Preisvergleich/Aktien-API
- Mail-API

# Tasks
- [x] [Wiederkehrende Preisabfrage](https://github.com/pda-aswe/casepreis/issues/1)
- [x] [Mitteilung eines Wunschpreises](https://github.com/pda-aswe/casepreis/issues/2)
- [x] [Versand von Produktinformationen / Aktieninformationen per Mail](https://github.com/pda-aswe/casepreis/issues/3)
- [x] [Proaktivität integrieren](https://github.com/pda-aswe/casepreis/issues/4)
- [x] [Aktion auf vordefinierte Sprachbefehle integrieren](https://github.com/pda-aswe/casepreis/issues/5)
- [x] [Einlesen der Präferenzen beim Start](https://github.com/pda-aswe/casepreis/issues/6)
- [x] Watches.json im Mainprocess und der Dockerdatei hinzufügen
- [x] Testen, wenn im Mainprozess integriert ist
- [x] Unittests hinzufügen

# Sprachbefehle
- "Informier mich, wenn die Apple-Aktie innerhalb der nächsten Woche für 120€ vorhanden ist"
- "Schicke mir weiter Informationen per Mail"

# Proaktivität
Wen ein Wunschpreis in dem Beobachtungszeitraum erreicht wurde. Mitteilung durch Sprachausgabe
