### ISSUE TITLE
News-Services

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#10]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicenews

# Tasks
- [x] [APIs auswählen](https://github.com/pda-aswe/servicenews/issues/1)
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicenews/issues/2)
- [x] [Anfrage für die Bereitstellung von Artikeln verarbeiten](https://github.com/pda-aswe/servicenews/issues/3)
- [x] [Ausgabe von einzelnen Artikeln mit Titel, Kurzbeschreibung und Langtext](https://github.com/pda-aswe/servicenews/issues/4)

News-APIs entweder in getrennten Repos oder hier zusammenfassen
