### ISSUE TITLE
Location-Service / Bluetooth-Service

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#11]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicelocation

# Tasks:
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicelocation/issues/2)
- [x] [Anfrage für die aktuelle Position verarbeiten](https://github.com/pda-aswe/servicelocation/issues/3)
- [x] [Bekanntgabe der aktuellen Position](https://github.com/pda-aswe/servicelocation/issues/5)
- [x] [Anfrage ob man sich im Auto befindet verarbeiten](https://github.com/pda-aswe/servicelocation/issues/4)
- [x] [Bekanntgabe ob man sich im Auto befindet](https://github.com/pda-aswe/servicelocation/issues/6)

Die Daten dieses Services werden wahrscheinlich alles nur Mock-Daten sein
