### ISSUE TITLE
Sport-Services

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#12]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicesport

# Tasks:
- [x] [APIs auswählen](https://github.com/pda-aswe/servicesport/issues/1)
- [ ] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicesport/issues/2)
- [x] [Verarbeitung der Anfrage für den nächsten Spieltermin](https://github.com/pda-aswe/servicesport/issues/3)
- [x] [Mitteilung des nächsten Spieltermins](https://github.com/pda-aswe/servicesport/issues/5)
- [x] [Verarbeitung der Anfrage des aktuellen Spielstands](https://github.com/pda-aswe/servicesport/issues/4)
- [x] [Mitteilung des aktuellen Spielstands](https://github.com/pda-aswe/servicesport/issues/6)

Sport-API entweder in getrennten Repos oder zusammenfügen
