### ISSUE TITLE
Aktien-Service

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#13]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicepreis

# Tasks
- [x] [API auswählen](https://github.com/pda-aswe/servicepreis/issues/1)
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicepreis/issues/2)
- [x] [Verarbeitung der Anfrage für die Suche des aktuellen Preis einer Aktie](https://github.com/pda-aswe/servicepreis/issues/3)
- [x] [Mitteilung des aktuellen Preis einer Aktie](https://github.com/pda-aswe/servicepreis/issues/4)
