### ISSUE TITLE
Mail-Service

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#14]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicemail

# Tasks
- [x] [API auswählen](https://github.com/pda-aswe/servicemail/issues/1)
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicemail/issues/2)
- [x]  [Verschicken von E-Mails](https://github.com/pda-aswe/servicemail/issues/3)
- [x] [Refactoring](https://github.com/pda-aswe/servicemail/issues/5)
- [x] [Tests](https://github.com/pda-aswe/servicemail/issues/6)
