### ISSUE TITLE
Use-Case Kalender

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#15]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/casekalender

# Services
- Kalender-Service

# Tasks
- [x] [Ausgabe von Terminerinnerungen](https://github.com/pda-aswe/casekalender/issues/1)
- [x] [Löschen von Terminen](https://github.com/pda-aswe/casekalender/issues/2)
- [x] [Erstellen von Terminen](https://github.com/pda-aswe/casekalender/issues/3)
- [x] [Aktion auf vordefinierte Sprachbefehle integrieren](https://github.com/pda-aswe/casekalender/issues/4)
- [x] [Einlesen der Präferenzen beim Start](https://github.com/pda-aswe/casekalender/issues/5)
- [x] [Proaktivität integrieren](https://github.com/pda-aswe/casekalender/issues/6)

# Sprachbefehle
- "Lösche den Termin ..."
- "Erstelle den Termin am ... mit dem Titel ..."
- "Verschiebe den nächsten Termin um ... Stunden"

# Proaktivität
- Automatische Mitteilung von Terminen 5 Minuten vor beginn.
