### ISSUE TITLE
Use-Case Sport

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#2]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/casesport

# Services
- Sport-APIs
- Kalender-API
- Wetter-API

# Tasks
- [ ] [Mitteilung von anstehenden Spielen](https://github.com/pda-aswe/casesport/issues/1)
- [ ] [Abspeicherung von anstehenden Spielen](https://github.com/pda-aswe/casesport/issues/2)
- [ ] [Mitteilung des aktuellen Spielstandes](https://github.com/pda-aswe/casesport/issues/3)
- [ ] [Proaktivität integrieren](https://github.com/pda-aswe/casesport/issues/4)
- [ ] [Aktion auf vordefinierte Sprachbefehle integrieren](https://github.com/pda-aswe/casesport/issues/5)
- [ ] [Einlesen der Präferenzen beim Start](https://github.com/pda-aswe/casesport/issues/6)

# Sprachbefehle
- "Wie ist der aktuelle Spielstand von ..."
- "Wie ist der letzte Spielstand von ..."

# Proaktivität
Automatische Mittelung des Spielergebnisses, wenn ein Spiel zu ende ist
