### ISSUE TITLE
Use-Case News

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#3]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/casenews

# Services
- mehrere News-APIs
- Location-API / Bluetooth-API

# Tasks
- [x] [Ausgabe von Kurznachrichten](https://github.com/pda-aswe/casenews/issues/1)
- [x] [Ausgabe von vollständigen Nachrichten](https://github.com/pda-aswe/casenews/issues/2)
- [x] [Nachrichten angepasst zum Standort](https://github.com/pda-aswe/casenews/issues/3)
- [x] [Proaktivität integrieren](https://github.com/pda-aswe/casenews/issues/4)
- [x] [Aktion auf vordefinierte Sprachbefehle integrieren](https://github.com/pda-aswe/casenews/issues/5)
- [x] [Einlesen der Präferenzen beim Start](https://github.com/pda-aswe/casenews/issues/6)

# Sprachbefehle
- "Lies den vollständigen Artikel vor"
- "Suche mehr Artikel"

# Proaktivität
Automatische Wiedergabe der Nachrichten während der Autofahrt
