### ISSUE TITLE
Use-Case Willkommensnachricht

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#4]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/casewelcome

# Services:
- Wetter-API
- Verkehrsinformations-API
- Kalender-API

# Tasks:
- [x] [Ausgabe der Wetterprognose](https://github.com/pda-aswe/casewelcome/issues/1)
- [x] [Ausgabe der Fahrtprognose](https://github.com/pda-aswe/casewelcome/issues/2)
- [x] [Ausgabe der Termine des Tags](https://github.com/pda-aswe/casewelcome/issues/3)
- [x] [Nachfrage nach Verkehrsmittel bei bestimmten Wetter & Verkehrslagen](https://github.com/pda-aswe/casewelcome/issues/4)
- [x] [Einlesen der Präferenzen beim Start](https://github.com/pda-aswe/casewelcome/issues/5)
- [x] [Proaktivität integrieren](https://github.com/pda-aswe/casewelcome/issues/6)
- [x] [Aktion auf vordefinierte Sprachbefehle integrieren](https://github.com/pda-aswe/casewelcome/issues/7)

# Sprachbefehle
- "Verwende das Auto"
- "Verwende das Fahrrad"
- "Verwende den ÖNV"
- "zu Fuß"

# Proaktivität:
Ausgabe der Informationen erfolgt automatisch zu einer gewünschten Zeit
