### ISSUE TITLE
Main-Process

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#5]
Repo: https://github.com/pda-aswe/main

# Tasks
- [x] [Umgang mit der Präferenzdatei](https://github.com/pda-aswe/main/issues/5)
- [x] [Präferenzen an Services bereitstellen](https://github.com/pda-aswe/main/issues/4)
- [x] [Präferenzen beim Start an alle Teilnehmer verschicken](https://github.com/pda-aswe/main/issues/3)
- [x] [Refactoring](https://github.com/pda-aswe/main/issues/15): Teil 1
- [x] [Automatisches Startskript für den PDA](https://github.com/pda-aswe/main/issues/2)
- [x] [Speech to Text](https://github.com/pda-aswe/main/issues/6)
- [x] [Text to Speech](https://github.com/pda-aswe/main/issues/7)
- [x] [Erstellung einer minimalen GUI](https://github.com/pda-aswe/main/issues/8)
- [x] [GUI überarbeiten](https://github.com/pda-aswe/main/issues/14)
- [x] [Erkennung von Ausgabekollisionen](https://github.com/pda-aswe/main/issues/9)
- [x] [Restriktiveren der Text to Speech](https://github.com/pda-aswe/main/issues/10)
- [x] [Docker Compose updaten](https://github.com/pda-aswe/main/issues/11)
- [x] [Tests schreiben](https://github.com/pda-aswe/main/issues/21)
- [x] [Googleanmeldung integrieren](https://github.com/pda-aswe/main/issues/23)
- [x] [GoogleToken in benötigte Container kopieren durch Compose](https://github.com/pda-aswe/main/issues/24)
