### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#6]
# Allgemein
In diesem Issue sollten alle allgemeinen Aufgaben festgehalten werden.

- [x] Wie ist Testcoverage gemeint
- [x] Sequenzdiagramm soll in einer Präsentation vorkommen von einen Use-Case
- [x] Architekturdesign muss enthalten sein --> Microservice-Architektur
- [x] 1 Designpattern muss irgendwo im Code enthalten sein --> Observer beim Überwachen der preferences.json

# Tasks
- [x] Testcoverage in Github Action anpassen
- [x] Issues erstellen
- [x] Repos erstellen
- [x] Erstellung eines Google-Accounts für Mail, Kalender, ...
- [x] Definition des Datenformats für Eventdaten --> JSON
- [x] Definition aller Präferenzen
- [x] Irgendwie müssen noch die allgemein Kalenderbefehle integriert werden für den PDA
- [x] Unittest-Testabdeckung durchschauen
