### ISSUE TITLE
Wetter-Service

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#7]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicewetter

# Tasks:
- [x] [API auswählen](https://github.com/pda-aswe/servicewetter/issues/1)
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicewetter/issues/2)
- [x] [Abfrage des aktuellen Standorts](https://github.com/pda-aswe/servicewetter/issues/3)
- [x] [Anfrage für das aktuelle Wetter verarbeiten](https://github.com/pda-aswe/servicewetter/issues/4)
- [x] [Ermittlung des aktuellen Wetters](https://github.com/pda-aswe/servicewetter/issues/6)
- [x] [Anfrage für das Wetter zu einer bestimmten Uhrzeit und Datum verarbeiten](https://github.com/pda-aswe/servicewetter/issues/5)
- [x] [Ermittlung des Wetters zu einer bestimmten Uhrzeit und Datum](https://github.com/pda-aswe/servicewetter/issues/7)
