### ISSUE TITLE
Verkehrsinformations-Service

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#8]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/serviceverkehrsinfos

# Tasks
- [x] [API auswählen](https://github.com/pda-aswe/serviceverkehrsinfos/issues/1)
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/serviceverkehrsinfos/issues/2)
- [x] [Bestimmung der Fahrtzeit zu einer bestimmten GPS-Koordinate. Fuß, Fahrrad, Auto & ÖMV](https://github.com/pda-aswe/serviceverkehrsinfos/issues/3)
- [x] [Anfrage für die Fahrtzeit zu einer bestimmten GPS-Koordinate verarbeiten](https://github.com/pda-aswe/serviceverkehrsinfos/issues/4)
- [x] [Refactoring](https://github.com/pda-aswe/serviceverkehrsinfos/issues/5)
- [x] [Tests](https://github.com/pda-aswe/serviceverkehrsinfos/issues/6)
- [x] [Präferenzen anpassen](https://github.com/pda-aswe/serviceverkehrsinfos/issues/7)
- [x] Main-Compose anpassen und Keys in Main anders verteilen
