### ISSUE TITLE
Kalender-Service

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/.github#9]
Liste aller Topics: https://github.com/pda-aswe/.github/blob/main/Topics.md
Repo: https://github.com/pda-aswe/servicekalender

# Tasks
- [x] [API auswählen](https://github.com/pda-aswe/servicekalender/issues/1)
- [x] [Definition der Event-Datenstruktur](https://github.com/pda-aswe/servicekalender/issues/2)
- [x] [Erinnerungshinweis 5 Minuten vor beginn eines Termin](https://github.com/pda-aswe/servicekalender/issues/3)
- [x] [Hinzufügen eines Termins](https://github.com/pda-aswe/servicekalender/issues/4)
- [x] [Löschen eines Termins](https://github.com/pda-aswe/servicekalender/issues/5)
- [x] [Bearbeiten eines Termins](https://github.com/pda-aswe/servicekalender/issues/6)
- [x] [Ausgabe aller Termine für einen bestimmten Tag](https://github.com/pda-aswe/servicekalender/issues/7)
